version: '3.7'
services:
  php:
    image: shopping_cart_application:latest
    volumes:
      - .:/var/www/html:cached
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_INI_XDEBUG__REMOTE_HOST: 10.254.254.254
#      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"
  nginx:
    image: nginx:1.17
    volumes:
      - .:/var/www/html:cached
      - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf:delegated
    ports:
      - "80:80"
    depends_on:
      - php
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
#    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      network:
        ipv4_address: 10.21.0.3

networks:
  network:
    ipam:
      config:
        - subnet: 10.21.0.0/24
